### PR TITLE
Update changelog for 1.5

### PR DESCRIPTION
**Pull request by dburgener**

### CODE REVIEW

**Comment by dburgener** [comment]
It's been about 10 months since the last release, and there are a couple of significant fixes - notably the gcc 14 fix, and the genfscon quoted path support.  I'd like to do a release in early January (to miss the holidays).  Exact date TBD.

**Comment by cgzones** [comment]
Could you maybe try to take a look on #250 for a next release?

**Comment by dburgener** [comment]
Yes.  Sorry about the extreme delay there.  I will aim to give it a review prior to the release.

**Comment by dburgener** [comment]
@cgzones I'm thinking about kicking this release today.  Any objections or anything else you want to make sure we get in first?

The asciidoctor PR is a draft, so I haven't really looked at it yet.  I imagine it can wait until after the release regardless?

**Comment by cgzones** [comment]
Everything is ready to go from my side. :rocket: 

> The asciidoctor PR is a draft, so I haven't really looked at it yet. I imagine it can wait until after the release regardless?

It'll need an update with the recent conventions addition and probably some wording tweaks...

**Pull request merged**
